# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - mine

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'
      - run: yarn install
      - run: yarn turbo:command build:internal --filter=@langchain/google-genai
      - run: |
          cd ./libs/langchain-google-genai
          ls -la
          sed -i "s/\@langchain\/google-genai/\@juji\/langchain-google-genai/" package.json
          cat package.json
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: langchain-google-genai
          path: libs/langchain-google-genai


  publish-npm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: rm -rf ./*
      - uses: actions/download-artifact@v4
        with:
          name: langchain-google-genai
      - run: ls -la
      - run: |
          rm -rf .yarn
          rm -rf .yarnrc.yml
          rm -rf node_modules
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
